# Generated by Django 3.2.6 on 2021-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfileupload',
            name='table',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('CUSTOMER_ADDRESS', 'CUSTOMER_ADDRESS'), ('CUSTOMER_OFFICE', 'CUSTOMER_OFFICE'), ('LOAN_AMOUNT', 'LOAN_AMOUNT'), ('BRANCH_DATA', 'BRANCH_DATA')], default='CUSTOMER', max_length=100),
            preserve_default=False,
        ),
    ]
