# Generated by Django 3.2.6 on 2021-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimain', '0002_excelfileupload_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfileupload',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
